### ISSUE TITLE
Error message with python version 3.6 +CUDA 8 +CuDNN 6

### ISSUE THREAD

**Issue by jcplu** [xavieryao/dqn-connect4#1]
...
Epoch 997/1000 | Loss 0.0743 | Epsilon 0.10 | Win count 775
Epoch 998/1000 | Loss 0.0127 | Epsilon 0.10 | Win count 776
Epoch 999/1000 | Loss 0.0154 | Epsilon 0.10 | Win count 777
Epoch 1000/1000 | Loss 0.0091 | Epsilon 0.10 | Win count 778

Traceback (most recent call last):
  File "C:\Users\xxx\Documents\Python\qlearning4k\examples\test_catch.py", line 21, in <module>
    agent.play(catch)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\qlearning4k-0.0.1-py3.6.egg\qlearning4k\agent.py", line 105, in play
    self.check_game_compatibility(game)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\qlearning4k-0.0.1-py3.6.egg\qlearning4k\agent.py", line 38, in check_game_compatibility
    if len(game_output_shape) != len(self.model.input_shape):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\topology.py", line 1039, in input_shape
    ' has multiple inbound nodes, '
AttributeError: The layer "sequential_1 has multiple inbound nodes, with different input shapes. Hence the notion of "input shape" is ill-defined for the layer. Use `get_input_shape_at(node_index)` instead.

Thanks for your help.

**Comment by meierale** [comment]
I've got the same error, also running python 3.6 (but without Cuda) on a MacBook Pro (High Sierra OS)

**Comment by meierale** [comment]
also test_snake.py fails with:
 File "/path/to/.../lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/path/to/.../lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 3 from 2 for 'conv2d_2/convolution' (op: 'Conv2D') with input shapes: [?,2,8,16], [3,3,16,32].

**Comment by xavieryao** [comment]
This repository is actually a fork of https://github.com/farizrahman4u/qlearning4k (I can't recall why I didn't fork it directly.). So you are referred to the original repository.
